neptune-mutual-blue/sdk

- package.json
- src/config/abis/IERC20Detailed.json
- src/config/store/definition.ts
- src/core/governance.ts
- src/core/index.ts
- src/core/liquidity.ts
- src/core/policy.ts
- src/core/resolution.ts
- src/index.ts
- Added resolution feature
- Fixed a bug in `getCoverFee` function
- Fixed a bug in `getBalance` function of liquidity
- Added `getBalanceOf` function in liquidity
- Added `approveStake` function in liquidity
- Moved `finalize` function from governance to resolution
- Updated store address
- Updated `IERC20Detailed` abi
> Release 0.2.8-beta

- package.json
- src/config/index.ts
- src/types/IStoreCandidate.ts
- src/types/index.ts
- src/utils/index.ts
- src/utils/store.ts
- yarn.lock
Added store multicall to bring smart contract data to the frontend
> Store Reader

- package.json
- src/core/cover.ts
- src/core/governance.ts
- src/core/liquidity.ts
- src/customTypings/xmlhttprequest.d.ts
- src/index.ts
- src/net/index.ts
- src/net/ipfs-client.ts
- src/types/Exceptions/GenericError.ts
- src/types/Exceptions/index.ts
- src/types/XMLHttpRequestReadyState.ts
- src/types/index.ts
- src/utils/ipfs.ts
- yarn.lock
- Dropped `ipfs-mini` and added `xmlhttprequest`
- Added a basic and simple IPFS client implementation
- Refactored `Cover` and `Governance` to use the new IPFS client
> Release v0.3.0-beta

- package.json
- src/config/store/definition.ts
- src/utils/store.ts
- Fixed bug in `getKey` function of store reader
- Updated SDK version
> Fixed Read Storage Bug

- package.json
- src/config/abis/IClaimsProcessor.json
- src/config/abis/ICover.json
- src/config/abis/IUniswapV2RouterLike.json
- src/config/store/definition.ts
- src/net/ipfs-client.ts
- src/registry/IUniswapV2FactoryLike.ts
- src/registry/IUniswapV2PairLike.ts
- src/registry/IUniswapV2RouterLike.ts
- src/registry/Stablecoin.ts
- src/registry/index.ts
- src/types/ICoverInfo.ts
- yarn.lock
- Added new registry contracts `Stablecoin`, `IUniswapV2FactoryLike`, `IUniswapV2PairLike`, and `IUniswapV2RouterLike`
- Updated type `ICoverInfo`
- Fixed a bug in `addString` function of IPFSClient
- Updated stores
- Updated namespace keys
- Updated ABIs
> Release v0.3.3-beta

- package.json
- src/config/abis/IPolicy.json
- src/config/abis/IResolution.json
- src/config/abis/IUnstakable.json
- src/config/abis/IVault.json
- src/config/store/definition.ts
- src/utils/key-util.ts
- Updated ABI
- Updated Store
- Updated namespace keys
> Release v0.3.4-beta

- package.json
- src/config/abis/ILiquidityEngine.json
- src/config/abis/IResolution.json
- src/config/abis/IUnstakable.json
- src/config/store/definition.ts
- src/utils/key-util.ts
- Updated ABIs
- Updated Store
- Updated Keys
> Release v0.3.6-beta

- package.json
- src/cache/browser-cache-provider.ts
- src/utils/store.ts
- Fixed expiry bug in browser cache provider
- Dropped console.log statement in store reader
> Release v0.3.8-beta

- package.json
- src/config/abis/IVault.json
- src/utils/key-util.ts
- Updated Vault ABI
- Updated namespace keys
> Release v0.4.0-beta

- package.json
- src/core/cover.ts
- src/core/cxToken.ts
- src/core/liquidity.ts
- src/core/policy.ts
- src/types/ICoverInfo.ts
- src/utils/key-util.ts
Changes Done:
- dev script updated for watch mode
- `requiresWhitelist` paramter added to `createCover` function
- cxToken function names fixed
- `referralCode` paramter added to vault `addLiquidity` function
- `referralCode` paramter added to policy `puchaseCover` function
- removed `initialLiquidity`, and added `requiresWhitelist`
& `exclusions` in `ICoverInfo` interface
> SDK updates

- package.json
- src/core/cover.ts
- src/core/cxToken.ts
- src/core/liquidity.ts
- src/core/policy.ts
- src/types/ICoverInfo.ts
- src/types/IStoreCandidate.ts
- src/utils/key-util.ts
- src/utils/store.ts
- Allow user to customize `function` and `arguments` while reading from store
- Bump sdk version
> Updated SDK

- package.json
- added a support for commonjs module, so it can work on unit testing
> CommonJS module support

- package.json
Updated build script to generate files in commonjs format as well
> Updated build script for cjs format

- src/core/claimsProcessor.ts
- src/core/cover.ts
- src/core/cxToken.ts
- src/core/governance.ts
- src/core/policy.ts
- src/core/resolution.ts
Updated functions to include `productKey` parameter for:
- `src/core/claimsProcessor.ts`:
- `validate`, `claim`
- `src/core/governance.ts`:
- `report`, `dispute`, `attest`, `refute`, `getIncidentDate`, 
`getReporter`, `getStatus`, `getStakes`, `getStakesOf`
- `src/core/resolution.ts`:
- `finalize`, `resolve`, `emergencyResolve`
- `src/core/cover.ts`
- `getCoverInfo`
- `src/core/policy.ts`
- `getCoverFee`, `purchaseCover`
- `src/core/cxToken.ts`
- `getCToken`, `getCTokenByExpiryDate`
> SDK functions update

- src/core/governance.ts
- src/core/resolution.ts
`src/core/governance.ts`:
- function invoking updated for `getMinStake`
`src/core/resolution.ts`:
- function `getResolutionDate` updated to `getResolutionTimestamp`
> Functions refactoring

- package.json
- src/config/abis/ICover.json
- src/config/abis/IGovernance.json
- src/config/abis/IWitness.json
- src/core/cxToken.ts
- src/net/ipfs-client.ts
- src/registry/BondPool.ts
- src/registry/ClaimsProcessor.ts
- src/registry/Cover.ts
- src/registry/Governance.ts
- src/registry/IERC20.ts
- src/registry/IUniswapV2FactoryLike.ts
- src/registry/IUniswapV2PairLike.ts
- src/registry/IUniswapV2RouterLike.ts
- src/registry/MemberResolver.ts
- src/registry/NPMToken.ts
- src/registry/PolicyContract.ts
- src/registry/Protocol.ts
- src/registry/Reassurance.ts
- src/registry/Resolution.ts
- src/registry/Stablecoin.ts
- src/registry/Staking.ts
- src/registry/StakingPools.ts
- src/registry/Store.ts
- src/registry/Vault.ts
- src/utils/pricing/lp.ts
- src/utils/pricing/pod.ts
- src/utils/pricing/token.ts
- test.js
- yarn.lock
- Updated ABIs according to the updated protocol
- Updated import statements to avoid cyclic dependencies
- Removed unused file
- Used `uuid.v4()` to generate a random string
- #38
> Release v0.4.8-beta

- src/config/networks/fuji.ts
- src/config/networks/mumbai.ts
- src/core/cover.ts
- src/core/governance.ts
- src/types/INetwork.ts
- Add a new property (hostname) on INetwork interface
- Refactor cover.ts and governance.ts to use the hostname instead of hard coding the permalink
> Permalink fix

- package.json
- src/config/abis/ICover.json
- src/config/abis/ILiquidityEngine.json
- src/config/abis/IPolicyAdmin.json
- src/config/abis/IProtocol.json
- src/config/abis/IVault.json
- src/config/networks/fuji.ts
- src/config/networks/mumbai.ts
- src/core/cover.ts
- src/core/governance.ts
- src/net/ipfs-client.ts
- src/types/ICoverInfo.ts
- src/types/INetwork.ts
- src/utils/ipfs.ts
- src/utils/key-util.ts
- tsconfig.json
- Updated Permalinks
- Removed [deprecated public Infura IPFS node](https://blog.infura.io/post/ipfs-public-api-and-gateway-deprecation) uris
- Fixed reassurance approval bug
- Improved reading from multiple IPFS nodes
- Updated ABIs and Keys
> Release v0.5.0-beta

- README.md
- package.json
- src/config/networks/arbitrum.ts
- src/config/networks/index.ts
- src/config/store/definition.ts
- src/types/ChainId.ts
- Added Arbitrum One Network support
- Chain ID: 42161
> Added arbitrum support

- package.json
- src/core/cover.ts
- src/core/governance.ts
- src/packages/ethers-multicall/src/provider.ts
- Removed `ipfs.write` usage from all methods to accept `ipfsHash` as method argument instead'
-  Updated version from `0.5.3-beta` to `0.5.4-beta` 
- Added Base Goerli network address to multicall providers
> Removed ipfs write from methods

- package.json
- src/config/networks/arbitrum.ts
- src/config/networks/base-goerli.ts
- src/config/networks/bsc.ts
- src/config/networks/ethereum.ts
- src/config/networks/index.ts
- src/config/store/definition.ts
- src/core/cover.ts
- src/types/ChainId.ts
- Updated swap router and factory addresses
- Updated WETH address
- Fixed minor bugs
> Release v0.5.6-beta

- .github/workflows/build.yml
- package.json
- rollup.config.js
- src/core/cover.ts
- Fixed lint errors
- Fixed build error
- Added github workflow to check lint errors and build errors
> Release v0.5.7-beta

- package.json
- src/config/networks/mumbai.ts
- Updated mumbai contract addresses
> Release v0.5.8-beta

- src/config/internal.ts
- src/config/networks/index.ts
- src/config/store/definition.ts
- src/config/store/index.ts
- src/index.ts
- src/types/SDKInternalStorage.ts
- src/types/index.ts
- To avoid depending on environment variables, added initialize function
- `initialize` function should be called before using any other functions
- `initialize` function is used to set store addresses for supported networks
> Add `initialize` function

- .eslintrc
- .github/workflows/build.yml
- README.md
- package.json
- src/net/ipfs-client.ts
- yarn.lock
- Removed `axios` and used fetch instead
- Updated README.md
- Updated eslint configuration and removed `ts-standard`
- Removed `rollup` and used typescript compiler `tsc`
- Add initialize function and removed dependency on environment variables
> Release v0.5.9-beta

- package.json
- src/config/internal.ts
- src/config/store/definition.ts
- src/config/store/index.ts
- src/types/Exceptions/InvalidChainIdError.ts
- Fixed bug in `getStoreAddressFromEnvironment`
> Release v0.5.10-beta
